### ISSUE TITLE
Company with most active rockets.(with percent)

### ISSUE THREAD

**Issue by Codehackerone** [DSCKGEC/Space-Missions#10]

**Comment by MainakNandi** [comment]
Hi, I want to contribute in this issue.

**Comment by Codehackerone** [comment]
Sure! Go Ahead.

**Comment by Codehackerone** [comment]
In case of any doubts, I will be hosting a session tomorrow at 8 pm, feel free to join that.

**Comment by MainakNandi** [comment]
Okay, thanks
