### ISSUE TITLE
Visualisation of Top 10 companies with highest success rate. 

### ISSUE THREAD

**Issue by Codehackerone** [DSCKGEC/Space-Missions#2]

**Comment by Mangalam0512** [comment]
Please assign me this issue

**Comment by Codehackerone** [comment]
Very well! But before that what kind of plot are you gonna use?

**Comment by Mangalam0512** [comment]
Scatterplot will be good ig.

**Comment by Codehackerone** [comment]
I am assigning this issue to you, although I suggest you go with countplot, catplot or most preferably pie chart.

**Comment by Mangalam0512** [comment]
Thank you for your suggestion and assigning me the project.
