### ISSUE TITLE
Visualisation of Launches by day of Companies

### ISSUE THREAD

**Issue by Codehackerone** [DSCKGEC/Space-Missions#7]
Refer to the notebook, you will find a similar thing is done for months. Plot day vs frequency. Frequency refers to all the combined missions of companies.
Refer to this notebook:-
https://colab.research.google.com/drive/1LsUBEn3x8beVJZAJf5cF1EY-RiMsrc-g?usp=sharing#scrollTo=ogfad7H3ddNg

**Comment by MainakNandi** [comment]
Can you describe more about this issue? I mean, **_total number of rockets launched by companies vs the Day_** should be plotted or **_for each company and for each day, the number of launches_** be plotted?

**Comment by Codehackerone** [comment]
Refer to the notebook, you will find a similar thing is done for months. Just plot day vs frequency. Frequency means all the combined missions of companies.
Refer this:-
https://colab.research.google.com/drive/1LsUBEn3x8beVJZAJf5cF1EY-RiMsrc-g?usp=sharing#scrollTo=ogfad7H3ddNg

**Comment by MainakNandi** [comment]
Okay, understood

**Comment by Codehackerone** [comment]
Do you want to work on this?

**Comment by debjitpal5040** [comment]
Assign me this please

**Comment by MainakNandi** [comment]
Yes, I do.

**Comment by Codehackerone** [comment]
Okay Cool!
